### ISSUE TITLE
A shorter version for the function gridpoints

### ISSUE THREAD

**Issue by empet** [COMODO-research/Comodo.jl#3]
Looking at the first  functions in Gibbon.jl I noticed that some of them are implemented following the MATLAB style, with many lines of code, that can be reduced to just a few.
For example `gridpoints` could be defined like this:
```
function grid3d(x::Vector{T}, y::Vector{T}, z::Vector{T}) where T<:Real
    reshape([GeometryBasics.Point{3, Float64}(x, y, z) for z in z, y in y, x in x], 
                             length(x)*length(y)*length(z))
end  
```
This version  reshapes a 3d grid, i.e. an `Array{Point3{Float64}, 3}`.
Now let us call both functions:
```
x=collect(range(0, 2, 10))
pts1=gridpoints(x, x, x)
pts2=grid3d(x,x,x) 
```      
They return the same vector of points.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @empet ! My background is MATLAB so yes I am shedding that "ugly accent" in my Julia language so keen to learn tips like this to improve. 

I wanted to check how fast these versions were. First I updated my function to be: 
```julia
function gridpoints(X::Vector{T}, Y=X::Vector{T}, Z=X::Vector{T}) where T<:Real 
    # Creates a 3D grid of GeometryBasics type 3D points based on the iterable input defining the ranges in the x, y, and z direction
    Vg = Vector{GeometryBasics.Point{3, Float64}}(undef,length(X)*length(Y)*length(Z)) # Allocate grid point set
    q = 0 # Initialize index 
    for x ∈ X # For all x entries
        for y ∈ Y # For all y entries
            for z ∈ Z # For all z entries
                q += 1 # Increment index
                Vg[q] = GeometryBasics.Point{3, Float64}(x,y,z) # Add the current point
            end
        end
    end
    return Vg # Return the grid point set
end
```
I did notice a mistake, i.e. I used to have ` Vg[q] = GeometryBasics.Point{3, Float64}([x,y,z])` (note the silly square brackets). But even after fixing that your solution is still mostly faster. I think I have a lot to learn. I would have thought that allocation of `Vg` helps, and that a `reshape` is costly (it is in MATLAB). I also thought keeping it as a range input e.g. `range(0, 2, 10)` rather than `collect(range(0, 2, 10))` would be faster. So I am surprised to see the efficiently of your simplified approach. 

Would you like me to change this or would you like to submit a pull request, so you are down as a contributor/co-author? 

Thanks again.

**Comment by Kevin-Mattheus-Moerman** [comment]
@empet note I've just moved/renamed the project. Just pinging so you could find your way here. Thanks again for the suggested change.

**Comment by empet** [comment]
Thank you for sending the new link. You may include the above code or modify it. The only remark is that inside `reshape` it must be `GeometryBasics.Point{3, T}`, not `GeometryBasics.Point{3, Float64}`.
